"""add_file_path_and_url_to_resumes

Revision ID: 0318513b4e03
Revises: af2d60eacb40
Create Date: 2025-12-10 22:09:12.845914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0318513b4e03'
down_revision: Union[str, Sequence[str], None] = 'af2d60eacb40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('resumes', sa.Column('file_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'file_url')
    op.drop_column('resumes', 'file_path')
    # ### end Alembic commands ###
