"""Add OptiHire schema with Supabase auth integration

Revision ID: 477144644922
Revises: 
Create Date: 2025-10-12 22:38:13.019735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '477144644922'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('job_description_id', sa.UUID(), nullable=True),
    sa.Column('resume_content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('job_description_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('keyword_score', sa.Integer(), nullable=False),
    sa.Column('formatting_score', sa.Integer(), nullable=False),
    sa.Column('section_score', sa.Integer(), nullable=False),
    sa.Column('matched_keywords', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('missing_keywords', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('keyword_density', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('has_contact_info', sa.Boolean(), nullable=False),
    sa.Column('has_summary', sa.Boolean(), nullable=False),
    sa.Column('has_experience', sa.Boolean(), nullable=False),
    sa.Column('has_education', sa.Boolean(), nullable=False),
    sa.Column('has_skills', sa.Boolean(), nullable=False),
    sa.Column('has_consistent_formatting', sa.Boolean(), nullable=False),
    sa.Column('has_bullet_points', sa.Boolean(), nullable=False),
    sa.Column('has_action_verbs', sa.Boolean(), nullable=False),
    sa.Column('is_scannable', sa.Boolean(), nullable=False),
    sa.Column('suggestions_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skills_version', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('keywords_rules_version', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('analysis_version', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('formatting_score >= 0 AND formatting_score <= 100', name='chk_formatting_score'),
    sa.CheckConstraint('keyword_score >= 0 AND keyword_score <= 100', name='chk_keyword_score'),
    sa.CheckConstraint('overall_score >= 0 AND overall_score <= 100', name='chk_overall_score'),
    sa.CheckConstraint('section_score >= 0 AND section_score <= 100', name='chk_section_score'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id', 'job_description_id', 'resume_content_hash', 'job_description_hash', 'skills_version', 'keywords_rules_version', 'analysis_version', name='uniq_analysis_deterministic')
    )
    op.create_index('idx_analysis_jobdesc', 'analysis_results', ['job_description_id'], unique=False)
    op.create_index('idx_analysis_resume', 'analysis_results', ['resume_id'], unique=False)
    op.create_index('idx_analysis_time', 'analysis_results', ['analyzed_at'], unique=False)
    op.create_index(op.f('ix_analysis_results_job_description_id'), 'analysis_results', ['job_description_id'], unique=False)
    op.create_index(op.f('ix_analysis_results_resume_id'), 'analysis_results', ['resume_id'], unique=False)
    op.create_table('industry_keywords',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('job_category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('keyword_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('importance_score', sa.Integer(), nullable=False),
    sa.Column('is_trending', sa.Boolean(), nullable=False),
    sa.Column('rules_version', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('importance_score >= 0 AND importance_score <= 100', name='chk_importance_score'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('industry', 'keyword', 'job_category', 'rules_version', name='uq_industry_keyword')
    )
    op.create_table('job_descriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('snippet', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('extracted_keywords', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('jd_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_descriptions_user_id'), 'job_descriptions', ['user_id'], unique=False)
    op.create_table('parse_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('error_class', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parse_tasks_file_id'), 'parse_tasks', ['file_id'], unique=False)
    op.create_index(op.f('ix_parse_tasks_status'), 'parse_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_parse_tasks_user_id'), 'parse_tasks', ['user_id'], unique=False)
    op.create_table('resume_certifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('certification_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('issuing_organization', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('credential_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('credential_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cert_resume', 'resume_certifications', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_certifications_resume_id'), 'resume_certifications', ['resume_id'], unique=False)
    op.create_table('resume_custom_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('section_title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('section_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_custom_resume', 'resume_custom_sections', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_custom_sections_resume_id'), 'resume_custom_sections', ['resume_id'], unique=False)
    op.create_table('resume_education',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('institution_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('degree_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('field_of_study', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('gpa', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('achievements', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('relevant_coursework', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_edu_resume', 'resume_education', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_education_resume_id'), 'resume_education', ['resume_id'], unique=False)
    op.create_table('resume_experiences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('job_title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('achievements', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('skills_used', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exp_resume', 'resume_experiences', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_experiences_resume_id'), 'resume_experiences', ['resume_id'], unique=False)
    op.create_table('resume_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('technologies_used', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('project_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('achievements', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_proj_resume', 'resume_projects', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_projects_resume_id'), 'resume_projects', ['resume_id'], unique=False)
    op.create_table('resume_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('skill_category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('proficiency_level', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('years_of_experience', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id', 'skill_name', name='uq_resume_skill')
    )
    op.create_index('idx_skill_resume', 'resume_skills', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_skills_resume_id'), 'resume_skills', ['resume_id'], unique=False)
    op.create_table('resume_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('section_order', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('linkedin_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('github_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('portfolio_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('professional_summary', sa.Text(), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resumes_content_hash', 'resumes', ['content_hash'], unique=False)
    op.create_index('idx_resumes_primary', 'resumes', ['user_id'], unique=True, postgresql_where='is_primary = TRUE')
    op.create_index('idx_resumes_user', 'resumes', ['user_id'], unique=False)
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('skill_corrections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('skill', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_skill_corrections_resume', 'skill_corrections', ['resume_id'], unique=False)
    op.create_index(op.f('ix_skill_corrections_resume_id'), 'skill_corrections', ['resume_id'], unique=False)
    op.create_index(op.f('ix_skill_corrections_user_id'), 'skill_corrections', ['user_id'], unique=False)
    op.create_table('suggestion_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('suggestion_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestion_interactions_suggestion_id'), 'suggestion_interactions', ['suggestion_id'], unique=False)
    op.create_index(op.f('ix_suggestion_interactions_user_id'), 'suggestion_interactions', ['user_id'], unique=False)
    op.create_table('suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('suggestion_text', sa.Text(), nullable=False),
    sa.Column('impact_level', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('rules_version', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("impact_level IN ('high', 'medium', 'low')", name='chk_suggestion_impact'),
    sa.CheckConstraint("state IN ('suggested', 'viewed', 'acted_upon', 'dismissed')", name='chk_suggestion_state'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_suggestions_analysis', 'suggestions', ['analysis_id'], unique=False)
    op.create_index('idx_suggestions_state', 'suggestions', ['state'], unique=False)
    op.create_index(op.f('ix_suggestions_analysis_id'), 'suggestions', ['analysis_id'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('object_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('storage_backend', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('presigned_expires_at', sa.DateTime(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('ttl_expires_at', sa.DateTime(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_user_id'), 'uploaded_files', ['user_id'], unique=False)
    op.create_table('user_onboarding_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('users',
    sa.Column('supabase_user_id', sa.UUID(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('linkedin_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('github_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('portfolio_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('preferred_roles', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('preferred_locations', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('preferred_salary_min', sa.Integer(), nullable=True),
    sa.Column('preferred_salary_max', sa.Integer(), nullable=True),
    sa.Column('years_of_experience', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('has_completed_onboarding', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('supabase_user_id', name='uq_users_supabase_user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_supabase_user_id'), 'users', ['supabase_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_supabase_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('user_onboarding_progress')
    op.drop_index(op.f('ix_uploaded_files_user_id'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_suggestions_analysis_id'), table_name='suggestions')
    op.drop_index('idx_suggestions_state', table_name='suggestions')
    op.drop_index('idx_suggestions_analysis', table_name='suggestions')
    op.drop_table('suggestions')
    op.drop_index(op.f('ix_suggestion_interactions_user_id'), table_name='suggestion_interactions')
    op.drop_index(op.f('ix_suggestion_interactions_suggestion_id'), table_name='suggestion_interactions')
    op.drop_table('suggestion_interactions')
    op.drop_index(op.f('ix_skill_corrections_user_id'), table_name='skill_corrections')
    op.drop_index(op.f('ix_skill_corrections_resume_id'), table_name='skill_corrections')
    op.drop_index('idx_skill_corrections_resume', table_name='skill_corrections')
    op.drop_table('skill_corrections')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_index('idx_resumes_user', table_name='resumes')
    op.drop_index('idx_resumes_primary', table_name='resumes', postgresql_where='is_primary = TRUE')
    op.drop_index('idx_resumes_content_hash', table_name='resumes')
    op.drop_table('resumes')
    op.drop_table('resume_templates')
    op.drop_index(op.f('ix_resume_skills_resume_id'), table_name='resume_skills')
    op.drop_index('idx_skill_resume', table_name='resume_skills')
    op.drop_table('resume_skills')
    op.drop_index(op.f('ix_resume_projects_resume_id'), table_name='resume_projects')
    op.drop_index('idx_proj_resume', table_name='resume_projects')
    op.drop_table('resume_projects')
    op.drop_index(op.f('ix_resume_experiences_resume_id'), table_name='resume_experiences')
    op.drop_index('idx_exp_resume', table_name='resume_experiences')
    op.drop_table('resume_experiences')
    op.drop_index(op.f('ix_resume_education_resume_id'), table_name='resume_education')
    op.drop_index('idx_edu_resume', table_name='resume_education')
    op.drop_table('resume_education')
    op.drop_index(op.f('ix_resume_custom_sections_resume_id'), table_name='resume_custom_sections')
    op.drop_index('idx_custom_resume', table_name='resume_custom_sections')
    op.drop_table('resume_custom_sections')
    op.drop_index(op.f('ix_resume_certifications_resume_id'), table_name='resume_certifications')
    op.drop_index('idx_cert_resume', table_name='resume_certifications')
    op.drop_table('resume_certifications')
    op.drop_index(op.f('ix_parse_tasks_user_id'), table_name='parse_tasks')
    op.drop_index(op.f('ix_parse_tasks_status'), table_name='parse_tasks')
    op.drop_index(op.f('ix_parse_tasks_file_id'), table_name='parse_tasks')
    op.drop_table('parse_tasks')
    op.drop_index(op.f('ix_job_descriptions_user_id'), table_name='job_descriptions')
    op.drop_table('job_descriptions')
    op.drop_table('industry_keywords')
    op.drop_index(op.f('ix_analysis_results_resume_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_job_description_id'), table_name='analysis_results')
    op.drop_index('idx_analysis_time', table_name='analysis_results')
    op.drop_index('idx_analysis_resume', table_name='analysis_results')
    op.drop_index('idx_analysis_jobdesc', table_name='analysis_results')
    op.drop_table('analysis_results')
    # ### end Alembic commands ###
